name: Build Workflow Matrix

on:
  workflow_call:
    inputs:
      inputFile:
        description: "The file that contains the JSON configuration of the matrix includes elements. Must come after a Checkout."
        required: false
        type: string
        default: ".github/workflows/matrix_includes.json"
      filter:
        description: "The JMESPath JSON query to apply to the input file."
        required: true
        type: string
      addInclude:
        description: "Wrap the output from the JSON query in an {include: ...} object."
        required: false
        type: boolean
        default: true
    outputs:
      matrix:
        description: "Return filtered matrix"
        value: ${{ jobs.matrix_prep.outputs.matrix }}

jobs:
  matrix_prep:
    name: "Read/Parse Strategy Matrix"
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: "Fetching Repository Contents"
        uses: actions/checkout@v3
        id: checkout
      - name: "Parse inputFile"
        uses: JoshuaTheMiller/conditional-build-matrix@main
        id: set-matrix
        with:          
          inputFile: ${{ inputs.inputFile || ".github/workflows/matrix_includes.json" }}
          filter: ${{ inputs.filter }}
          addInclude: ${{ inputs.addInclude || true }}
